In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/usr/local/python/3.12.1/lib/python3.12/site-packages/numpy/__init__.py'>

## Creating arrays ##

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1, 2, 3, 5, 7])
a

array([1, 2, 3, 5, 7])

In [7]:
a[2] = 10
a

array([ 1,  2, 10,  5,  7])

In [8]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [9]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dementional arrays

In [10]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])

In [12]:
n[2,2]

np.int64(9)

In [13]:
n[0,1] = 4
n[0,1]
n[2] = [1,1,1]
n

array([[1, 4, 3],
       [4, 5, 6],
       [1, 1, 1]])

In [14]:
n[:, 1] = [1, 3, 4]
n

array([[1, 1, 3],
       [4, 3, 6],
       [1, 4, 1]])

## Randomly Generated arrays

In [15]:
np.random.seed(2)
100*np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [16]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [17]:
b = (10 + (a*2)) ** 2 / 100
b

array([1.44, 1.96, 9.  , 4.  , 5.76])

## Element-wise operations

In [18]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

## Comparison Operations

In [19]:
a 

array([0, 1, 2, 3, 4])

In [20]:
a >= 2

array([False, False,  True,  True,  True])

In [21]:
b

array([1.44, 1.96, 9.  , 4.  , 5.76])

In [22]:
a > b

array([False, False, False, False, False])

In [23]:
a[a > b]

array([], dtype=int64)

## Summarizin operations

In [24]:
a

array([0, 1, 2, 3, 4])

In [25]:
a.min()

np.int64(0)

In [26]:
a.sum()

np.int64(10)

In [27]:
a.mean()

np.float64(2.0)

In [28]:
a.std()

np.float64(1.4142135623730951)

In [29]:
n.sum()

np.int64(24)

## Vector

In [30]:
u = np.array([2,4,5,6])
v = np.array([1, 0, 0, 2])

In [31]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
        
    return result 

In [32]:
vector_vector_multiplication(u, v)

np.float64(14.0)

In [33]:
u.dot(v)

np.int64(14)

In [34]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [35]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [36]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
       result[i] =  vector_vector_multiplication(U[i], v)
        
    return result

In [37]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [38]:
U.dot(v)

array([14,  5,  5])

In [39]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])

In [40]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_columns = V.shape[1]

    result = np.zeros((num_rows, num_columns))

    for i in range(num_columns):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:,i] = Uvi

    return result


In [41]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [42]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity Matrix

In [43]:
 I = np.eye(3)

In [44]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [45]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [46]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [47]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [48]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Pandas

In [54]:
import pandas as pd